// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Algorithm',
      items: [{type: 'autogenerated', dirName: 'algorithm'}],
    },
    {
      type: 'category',
      label: 'BackEnd',
      items: [{type: 'autogenerated', dirName: 'backend'}],
    },
    {
      type: 'category',
      label: 'FrontEnd',
      items: [{type: 'autogenerated', dirName: 'frontend'}],
    },
    {
      type: 'category',
      label: 'ML',
      items: [{type: 'autogenerated', dirName: 'ml'}],
    },
    {
      type: 'category',
      label: 'System Design',
      link: {
        type: 'generated-index',
        title: 'System Design',
      },
      items: [{type: 'autogenerated', dirName: 'system-designs'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
